parserOptions:
  ecmaVersion: 6
  project: tsconfig.json

env:
  browser: true

extends:
  - airbnb-typescript
  - airbnb/hooks
  - plugin:@typescript-eslint/recommended
  - plugin:import/errors
  - plugin:import/warnings

rules:
  react/react-in-jsx-scope: off
  jsx-a11y/accessible-emoji: off
  jsx-a11y/anchor-is-valid: off
  jsx-a11y/label-has-associated-control: off

  react/jsx-curly-spacing:
    - error
    - when: always
      attributes: false
      children: true

  array-bracket-spacing:
    - error
    - always